language: node_js
node_js:
- '4'
- '5'
- '6'
- node
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
- npm install istanbul -g
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
env:
  global:
    secure: 'oviuSejh8lPMBFiUWrVhzwv4b4QEKCoOWRY4HpZGjkON+xTH0BEUqtEvC9OmLbckt+S/nlQv4ucNTm5NBUYEQvOUdm68ybiL1NIu9IjBhqbUBhblawVUd2gLQps1bhFXzlcpmbWYsMQ6CJNeGbK5KGlCwa7uTPRHRyE8+0YiNUefDK+lRHvYSWxCGVCjjQTFVj9axVQX6+N3TrYdRuJ+0SxZO9l2vUtPUqJWilJog8D16BygR97bhVkOBGSJD3u1Ts/WVaSxbGo5H8AQHNMyKjdUhl6sQtZ/Cfc3tGdtDoQqSuzGUdFYNAP5WJjRntJnv6KOIDsmPJeb2J/4wD+A3fg1841urYU9tq7y6a9WiVyOp3uvOG7GY2NIwF0qefHmhah5YcWZI4g11r2DrpDRGAW8y0TD2qHPZCYzSS6RXF/qR637di+riuzoP0joCvUECUIDBPArPLa9W1+BI9cymb1bhGqzKFnmwxqbdoWofTXDRTK41dmB4fT1AZWhXurrR49W79wfx+BrWqiKRaPnI6s9EjRXsQQCjOcC2FQtcXi+bo0H/C8aBsaRPAfqrDQiQjwaMDoVebioBWW8w01QLFpCAGYu88xXoQXHR9TNPF906mJjitUikvk+BVPXtNJPiIKICRjROwxZIi0g6xpDev671fyQa5WgbfAVpBBKJuw='
